compressionLevel: 0
defaultSemverRangePrefix: ^
enableGlobalCache: false
nodeLinker: node-modules
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-postinstall-dev.cjs
    spec: https://raw.githubusercontent.com/sachinraja/yarn-plugin-postinstall-dev/main/bundles/%40yarnpkg/plugin-postinstall-dev.js
  - path: .yarn/plugins/@yarnpkg/plugin-conventional-version.cjs
    spec: https://raw.githubusercontent.com/christophehurpeau/yarn-plugin-conventional-version/main/bundles/%40yarnpkg/plugin-conventional-version.cjs
supportedArchitectures:
  cpu:
    - x64
    - arm64
  os:
    - linux
    - darwin
  libc:
    - glibc
    - musl
