allowBuilds:
  esbuild: true
  unrs-resolver: true
dedupePeerDependents: true
minimumReleaseAge: 3600
minimumReleaseAgeExclude:
  - "@pob/*"
  - pob
  - pob-dependencies
  - check-package-dependencies
  - alouette
  - alouette-icons
  - nightingale
  - nightingale-logger
nodeLinker: hoisted
savePrefix: ^
