name: Push CI
permissions:
  contents: read
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x, 24.x]

    steps:
      - uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 11

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Checks
        run: pnpm run checks
        if: startsWith(matrix.node-version, '24.')

      - name: Build
        run: pnpm run build
        if: startsWith(matrix.node-version, '24.')

      - name: Format
        run: pnpm run format:check
        if: startsWith(matrix.node-version, '24.')

      - name: Typescript
        run: pnpm run tsc
        if: startsWith(matrix.node-version, '24.')

      - name: Eslint
        run: pnpm run lint:eslint
        if: startsWith(matrix.node-version, '24.')

      - name: Check nothing was forgotten before commit
        if: startsWith(matrix.node-version, '24.')
        run: pnpm exec repository-check-dirty

      - name: Generate Test Coverage
        run: pnpm run test:coverage:json
        if: startsWith(matrix.node-version, '24.')
        env:
          CI: true

      - name: Send results to codecov
        uses: codecov/codecov-action@v6
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
        if: startsWith(matrix.node-version, '24.') && github.actor != 'dependabot[bot]'
